- hosts: linux-hosts
  user: python-service-runner
  tasks:
        - name: Copy Python script
          copy: 
            src: ./{{service_name}}.py
            dest: ~/{{service_name}}.py
            mode: u+rw,g-wx,o-rwx
        - name: Start Python scripts as a service
          command: /bin/bash -c "nohup python ~/{{service_name}}.py > ~/{{service_name}}.log 2>&1 &"

- hosts: windows-hosts
  tasks:
        - name: Copy Python script
          copy: 
            src: ./{{service_name}}.py
            dest: ~/application.py
            mode: u+rw,g-wx,o-rwx
        - name: Install Python script as a service
          command: nssm install {{service_name}} ~/{{service_name}}.py
        - name: Install Python script as a service
          command: nssm set {{service_name}} AppDirectory ~/
        - name: Redirect stdout to a log file
          command: nssm set {{service_name}} AppStdOut ~/{{service_name}}.log

